import Utils from '../../../../../utils/utils';

export const Regioes = {
  GPOA: 'GPOA',
  RSInterior: 'RSInterior',
  SCSul: 'SCSul',
  SCNorte: 'SCNorte',
  PR: 'PR',
};

export const Cargos = {
  ExecutivoDeContas: 'ExecutivoDeContas',
  AnalistaAdministrativo: 'AnalistaAdministrativo',
  AnalistaComercial: 'AnalistaComercial',
  AnalistaDeAdmPessoal: 'AnalistaDeAdmPessoal',
  AnalistaDeCustos: 'AnalistaDeCustos',
  AnalistaDeFaturamento: 'AnalistaDeFaturamento',
  AnalistaDeGestãoPessoas: 'AnalistaDeGestãoPessoas',
  AnalistaFinanceiro: 'AnalistaFinanceiro',
  AnalistaMarketing: 'AnalistaMarketing',
  AnalistaSocialMidia: 'AnalistaSocialMidia',
  AssistenteAdministrativo: 'AssistenteAdministrativo',
  AssistenteContabil: 'AssistenteContabil',
  AssistenteDeAdmPessoal: 'AssistenteDeAdmPessoal',
  AssistenteDeControle: 'AssistenteDeControle',
  AssistenteDeFaturamento: 'AssistenteDeFaturamento',
  AssistenteDeGestãoPessoas: 'AssistenteDeGestãoPessoas',
  AssistenteDeProdutividade: 'AssistenteDeProdutividade',
  AssistenteDeRecebimento: 'AssistenteDeRecebimento',
  AssistenteDeSuprimentos: 'AssistenteDeSuprimentos',
  AssistenteFiscal: 'AssistenteFiscal',
  Assistente_AnalistaComercial: 'Assistente_AnalistaComercial',
  AuxiliarContabil: 'AuxiliarContabil',
  AuxiliarDeMarketing: 'AuxiliarDeMarketing',
  AuxiliarJuridico: 'AuxiliarJuridico',
  EspecialistaContabil: 'EspecialistaContabil',
  EspecialistaFinanceiro: 'EspecialistaFinanceiro',
  Estagiario: 'Estagiario',
  GerenteDeMarketing: 'GerenteDeMarketing',
  GerenteDeVendas: 'GerenteDeVendas',
  GerenteFinanceiro: 'GerenteFinanceiro',
  GerenteGeral: 'GerenteGeral',
  GerenteIndustrial: 'GerenteIndustrial',
  GerenteJurídicoERh: 'GerenteJurídicoERh',
  GerenteLogistica: 'GerenteLogistica',
  JovemAprendiz: 'JovemAprendiz',
  OperadorDeCervejaria: 'OperadorDeCervejaria',
  SupervisorDeControladoria: 'SupervisorDeControladoria',
  SupervisorDeGrandesContas: 'SupervisorDeGrandesContas',
  SupervisorDeProdução: 'SupervisorDeProdução',
  SupervisorDeSuprimentos: 'SupervisorDeSuprimentos',
  SupervisorDeTradeEMarketing: 'SupervisorDeTradeEMarketing',
  SupervisorDeVendas: 'SupervisorDeVendas',
  Vendedor: 'Vendedor',
};

export default [
  {
    matricula: 111249,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.ExecutivoDeContas,
    admissao: Utils.Mes(2020, 3),
    salarioBase: 0,
    salarioBaseInicial: 2567,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1973, 11),
    comercial: true,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 1,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 111265,
    setor: 'LOGISTICA',
    nomeCargo: Cargos.GerenteLogistica,
    admissao: Utils.Mes(2020, 9),
    salarioBase: 0,
    salarioBaseInicial: 7143,
    funcaoGratificada: true,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1973, 1),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 111218,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.Vendedor,
    admissao: Utils.Mes(2019, 1),
    salarioBase: 0,
    salarioBaseInicial: 1965,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1973, 7),
    comercial: true,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 2,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 111247,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.Vendedor,
    admissao: Utils.Mes(2020, 3),
    salarioBase: 0,
    salarioBaseInicial: 1965,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1988, 4),
    comercial: true,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 0,
    regiao: Regioes.RSInterior,
  },
  {
    matricula: 111259,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.Vendedor,
    admissao: Utils.Mes(2020, 3),
    salarioBase: 0,
    salarioBaseInicial: 1965,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1977, 9),
    comercial: true,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 1,
    regiao: Regioes.RSInterior,
  },
  {
    matricula: 611319,
    setor: 'GESTÃO PESSOAS',
    nomeCargo: Cargos.AssistenteDeAdmPessoal,
    admissao: Utils.Mes(2019, 12),
    salarioBase: 0,
    salarioBaseInicial: 2041,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1988, 6),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'F',
    qtdFilhos: 1,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 111231,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.SupervisorDeVendas,
    admissao: Utils.Mes(2019, 6),
    salarioBase: 0,
    salarioBaseInicial: 3531,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1976, 4),
    comercial: true,
    estadoResidencia: 'SC',
    sexo: 'M',
    qtdFilhos: 2,
    regiao: Regioes.SCNorte,
  },
  {
    matricula: 611305,
    setor: 'GESTÃO PESSOAS',
    nomeCargo: Cargos.AnalistaDeAdmPessoal,
    admissao: Utils.Mes(2019, 3),
    salarioBase: 0,
    salarioBaseInicial: 3062,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1974, 9),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'F',
    qtdFilhos: 2,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 111193,
    setor: 'INDUSTRIA',
    nomeCargo: Cargos.AnalistaAdministrativo,
    admissao: Utils.Mes(2002, 9),
    salarioBase: 0,
    salarioBaseInicial: 4266,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1978, 11),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 2,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 111230,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.SupervisorDeVendas,
    admissao: Utils.Mes(2019, 6),
    salarioBase: 0,
    salarioBaseInicial: 3531,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1983, 6),
    comercial: true,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 2,
    regiao: Regioes.SCSul,
  },
  {
    matricula: 111257,
    setor: 'INDUSTRIA',
    nomeCargo: Cargos.GerenteIndustrial,
    admissao: Utils.Mes(2020, 3),
    salarioBase: 0,
    salarioBaseInicial: 10971,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1967, 12),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 111254,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.Vendedor,
    admissao: Utils.Mes(2020, 3),
    salarioBase: 0,
    salarioBaseInicial: 1965,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1983, 9),
    comercial: true,
    estadoResidencia: 'SC',
    sexo: 'M',
    qtdFilhos: 2,
    regiao: Regioes.SCNorte,
  },
  {
    matricula: 611304,
    setor: 'MARKETING',
    nomeCargo: Cargos.AuxiliarDeMarketing,
    admissao: Utils.Mes(2019, 3),
    salarioBase: 0,
    salarioBaseInicial: 1656,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1998, 4),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'F',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 111256,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.ExecutivoDeContas,
    admissao: Utils.Mes(2020, 3),
    salarioBase: 0,
    salarioBaseInicial: 2567,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1971, 10),
    comercial: true,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 1,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 111229,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.SupervisorDeGrandesContas,
    admissao: Utils.Mes(2019, 6),
    salarioBase: 0,
    salarioBaseInicial: 3531,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1978, 10),
    comercial: true,
    estadoResidencia: 'SC',
    sexo: 'M',
    qtdFilhos: 1,
    regiao: Regioes.SCSul,
  },
  {
    matricula: 111245,
    setor: 'JOVEM APRENDIZ',
    nomeCargo: Cargos.JovemAprendiz,
    admissao: Utils.Mes(2020, 2),
    salarioBase: 0,
    salarioBaseInicial: 616,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(2000, 11),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 611307,
    setor: 'GESTÃO PESSOAS',
    nomeCargo: Cargos.AssistenteDeGestãoPessoas,
    admissao: Utils.Mes(2019, 4),
    salarioBase: 0,
    salarioBaseInicial: 2552,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1991, 1),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'F',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 611312,
    setor: 'JOVEM APRENDIZ',
    nomeCargo: Cargos.JovemAprendiz,
    admissao: Utils.Mes(2019, 9),
    salarioBase: 0,
    salarioBaseInicial: 568,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(2003, 12),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'F',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 111243,
    setor: 'FINANCEIRO',
    nomeCargo: Cargos.AnalistaDeCustos,
    admissao: Utils.Mes(2017, 8),
    salarioBase: 0,
    salarioBaseInicial: 3539,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1985, 12),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 111250,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.Vendedor,
    admissao: Utils.Mes(2020, 3),
    salarioBase: 0,
    salarioBaseInicial: 1965,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1983, 5),
    comercial: true,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 2,
    regiao: Regioes.RSInterior,
  },
  {
    matricula: 611252,
    setor: 'FINANCEIRO',
    nomeCargo: Cargos.AnalistaFinanceiro,
    admissao: Utils.Mes(2015, 8),
    salarioBase: 0,
    salarioBaseInicial: 3365,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1976, 11),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'F',
    qtdFilhos: 1,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 611270,
    setor: 'FINANCEIRO',
    nomeCargo: Cargos.AssistenteAdministrativo,
    admissao: Utils.Mes(2016, 10),
    salarioBase: 0,
    salarioBaseInicial: 2509,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1981, 6),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'F',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 111266,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.Vendedor,
    admissao: Utils.Mes(2020, 10),
    salarioBase: 0,
    salarioBaseInicial: 1965,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1971, 12),
    comercial: true,
    estadoResidencia: 'SC',
    sexo: 'M',
    qtdFilhos: 0,
    regiao: Regioes.SCNorte,
  },
  {
    matricula: 111235,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.SupervisorDeTradeEMarketing,
    admissao: Utils.Mes(2019, 8),
    salarioBase: 0,
    salarioBaseInicial: 4695,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1976, 11),
    comercial: true,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 1,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 111238,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.ExecutivoDeContas,
    admissao: Utils.Mes(2019, 9),
    salarioBase: 0,
    salarioBaseInicial: 2567,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1985, 11),
    comercial: true,
    estadoResidencia: 'SC',
    sexo: 'M',
    qtdFilhos: 2,
    regiao: Regioes.SCNorte,
  },
  {
    matricula: 611321,
    setor: 'INDUSTRIA',
    nomeCargo: Cargos.OperadorDeCervejaria,
    admissao: Utils.Mes(2020, 11),
    salarioBase: 0,
    salarioBaseInicial: 2000,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1991, 12),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 611268,
    setor: 'FINANCEIRO',
    nomeCargo: Cargos.AssistenteContabil,
    admissao: Utils.Mes(2016, 8),
    salarioBase: 0,
    salarioBaseInicial: 1963,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1990, 5),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'F',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 111255,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.Vendedor,
    admissao: Utils.Mes(2020, 3),
    salarioBase: 0,
    salarioBaseInicial: 1965,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1991, 8),
    comercial: true,
    estadoResidencia: 'SC',
    sexo: 'M',
    qtdFilhos: 0,
    regiao: Regioes.SCSul,
  },
  {
    matricula: 611320,
    setor: 'GESTÃO PESSOAS',
    nomeCargo: Cargos.AuxiliarJuridico,
    admissao: Utils.Mes(2020, 1),
    salarioBase: 0,
    salarioBaseInicial: 1735,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1999, 9),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 111261,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.ExecutivoDeContas,
    admissao: Utils.Mes(2020, 4),
    salarioBase: 0,
    salarioBaseInicial: 2567,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1978, 12),
    comercial: true,
    estadoResidencia: 'SC',
    sexo: 'M',
    qtdFilhos: 1,
    regiao: Regioes.SCSul,
  },
  {
    matricula: 111263,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.Vendedor,
    admissao: Utils.Mes(2020, 4),
    salarioBase: 0,
    salarioBaseInicial: 1965,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1973, 11),
    comercial: true,
    estadoResidencia: 'SC',
    sexo: 'M',
    qtdFilhos: 1,
    regiao: Regioes.SCSul,
  },
  {
    matricula: 111262,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.ExecutivoDeContas,
    admissao: Utils.Mes(2020, 4),
    salarioBase: 0,
    salarioBaseInicial: 2567,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1976, 1),
    comercial: true,
    estadoResidencia: 'PR',
    sexo: 'M',
    qtdFilhos: 2,
    regiao: Regioes.PR,
  },
  {
    matricula: 611317,
    setor: 'FINANCEIRO',
    nomeCargo: Cargos.AssistenteFiscal,
    admissao: Utils.Mes(2019, 11),
    salarioBase: 0,
    salarioBaseInicial: 2348,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1987, 7),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 2,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 111213,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.ExecutivoDeContas,
    admissao: Utils.Mes(2019, 7),
    salarioBase: 0,
    salarioBaseInicial: 2567,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1977, 12),
    comercial: true,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 1,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 111198,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.GerenteGeral,
    admissao: Utils.Mes(2014, 7),
    salarioBase: 0,
    salarioBaseInicial: 11629,
    funcaoGratificada: true,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1979, 6),
    comercial: true,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 1,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 111244,
    setor: 'FINANCEIRO',
    nomeCargo: Cargos.SupervisorDeSuprimentos,
    admissao: Utils.Mes(2019, 8),
    salarioBase: 0,
    salarioBaseInicial: 5102,
    funcaoGratificada: true,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1984, 3),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 111260,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.SupervisorDeVendas,
    admissao: Utils.Mes(2020, 3),
    salarioBase: 0,
    salarioBaseInicial: 3531,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1970, 11),
    comercial: true,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 1,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 111253,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.ExecutivoDeContas,
    admissao: Utils.Mes(2020, 3),
    salarioBase: 0,
    salarioBaseInicial: 2567,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1975, 3),
    comercial: true,
    estadoResidencia: 'SC',
    sexo: 'M',
    qtdFilhos: 0,
    regiao: Regioes.SCSul,
  },
  {
    matricula: 111194,
    setor: 'INDUSTRIA',
    nomeCargo: Cargos.SupervisorDeProdução,
    admissao: Utils.Mes(2013, 11),
    salarioBase: 0,
    salarioBaseInicial: 6833,
    funcaoGratificada: true,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1981, 3),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 611216,
    setor: 'MARKETING',
    nomeCargo: Cargos.GerenteDeMarketing,
    admissao: Utils.Mes(2014, 2),
    salarioBase: 0,
    salarioBaseInicial: 5547,
    funcaoGratificada: true,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1976, 11),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'F',
    qtdFilhos: 1,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 611315,
    setor: 'FINANCEIRO',
    nomeCargo: Cargos.AuxiliarContabil,
    admissao: Utils.Mes(2019, 10),
    salarioBase: 0,
    salarioBaseInicial: 1633,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1995, 8),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'F',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 111239,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.AnalistaComercial,
    admissao: Utils.Mes(2019, 9),
    salarioBase: 0,
    salarioBaseInicial: 4082,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1978, 9),
    comercial: true,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 111217,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.GerenteDeVendas,
    admissao: Utils.Mes(2018, 10),
    salarioBase: 0,
    salarioBaseInicial: 10940,
    funcaoGratificada: true,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1975, 3),
    comercial: true,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 1,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 611293,
    setor: 'FINANCEIRO',
    nomeCargo: Cargos.EspecialistaContabil,
    admissao: Utils.Mes(2018, 5),
    salarioBase: 0,
    salarioBaseInicial: 7198,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1981, 9),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 1,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 111248,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.Vendedor,
    admissao: Utils.Mes(2020, 3),
    salarioBase: 0,
    salarioBaseInicial: 1965,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1984, 9),
    comercial: true,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 1,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 111199,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.ExecutivoDeContas,
    admissao: Utils.Mes(2015, 2),
    salarioBase: 0,
    salarioBaseInicial: 2567,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1983, 3),
    comercial: true,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 1,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 111242,
    setor: 'FINANCEIRO',
    nomeCargo: Cargos.AssistenteDeProdutividade,
    admissao: Utils.Mes(2019, 11),
    salarioBase: 0,
    salarioBaseInicial: 2348,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1995, 5),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'F',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 111228,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.ExecutivoDeContas,
    admissao: Utils.Mes(2019, 6),
    salarioBase: 0,
    salarioBaseInicial: 2567,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1980, 11),
    comercial: true,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 2,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 611298,
    setor: 'FINANCEIRO',
    nomeCargo: Cargos.AssistenteAdministrativo,
    admissao: Utils.Mes(2011, 7),
    salarioBase: 0,
    salarioBaseInicial: 2509,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1983, 9),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 611261,
    setor: 'GESTÃO PESSOAS',
    nomeCargo: Cargos.AnalistaDeGestãoPessoas,
    admissao: Utils.Mes(2016, 5),
    salarioBase: 0,
    salarioBaseInicial: 4197,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1984, 4),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'F',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 611306,
    setor: 'FINANCEIRO',
    nomeCargo: Cargos.EspecialistaFinanceiro,
    admissao: Utils.Mes(2019, 4),
    salarioBase: 0,
    salarioBaseInicial: 4620,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1991, 2),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 111258,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.Vendedor,
    admissao: Utils.Mes(2020, 3),
    salarioBase: 0,
    salarioBaseInicial: 1965,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1989, 6),
    comercial: true,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 2,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 611217,
    setor: 'FINANCEIRO',
    nomeCargo: Cargos.GerenteFinanceiro,
    admissao: Utils.Mes(2014, 2),
    salarioBase: 0,
    salarioBaseInicial: 10600,
    funcaoGratificada: true,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1900, 1),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'F',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 611018,
    setor: 'GESTÃO PESSOAS',
    nomeCargo: Cargos.GerenteJurídicoERh,
    admissao: Utils.Mes(2003, 11),
    salarioBase: 0,
    salarioBaseInicial: 9600,
    funcaoGratificada: true,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1979, 8),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'F',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 700001,
    setor: 'LOGISTICA',
    nomeCargo: Cargos.AssistenteAdministrativo,
    admissao: Utils.Mes(2021, 1),
    salarioBase: 0,
    salarioBaseInicial: 2500,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1984, 4),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'F',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 700002,
    setor: 'LOGISTICA',
    nomeCargo: Cargos.AssistenteAdministrativo,
    admissao: Utils.Mes(2021, 1),
    salarioBase: 0,
    salarioBaseInicial: 2500,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1996, 4),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 700003,
    setor: 'INDUSTRIA',
    nomeCargo: Cargos.AssistenteDeControle,
    admissao: Utils.Mes(2021, 1),
    salarioBase: 0,
    salarioBaseInicial: 2500,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1900, 1),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 700004,
    setor: 'FINANCEIRO',
    nomeCargo: Cargos.SupervisorDeControladoria,
    admissao: Utils.Mes(2021, 2),
    salarioBase: 0,
    salarioBaseInicial: 7150,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1900, 1),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 700005,
    setor: 'FINANCEIRO',
    nomeCargo: Cargos.AssistenteDeSuprimentos,
    admissao: Utils.Mes(2021, 1),
    salarioBase: 0,
    salarioBaseInicial: 2000,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1900, 1),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 700006,
    setor: 'FINANCEIRO',
    nomeCargo: Cargos.AnalistaDeFaturamento,
    admissao: Utils.Mes(2021, 1),
    salarioBase: 0,
    salarioBaseInicial: 3000,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1900, 1),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'F',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 700007,
    setor: 'FINANCEIRO',
    nomeCargo: Cargos.AssistenteDeRecebimento,
    admissao: Utils.Mes(2021, 1),
    salarioBase: 0,
    salarioBaseInicial: 2200,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1900, 1),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'F',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 700008,
    setor: 'FINANCEIRO',
    nomeCargo: Cargos.AssistenteDeFaturamento,
    admissao: Utils.Mes(2021, 1),
    salarioBase: 0,
    salarioBaseInicial: 2200,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1900, 1),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 700009,
    setor: 'MARKETING',
    nomeCargo: Cargos.Estagiario,
    admissao: Utils.Mes(2021, 2),
    salarioBase: 0,
    salarioBaseInicial: 1500,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1900, 1),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'F',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 700010,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.ExecutivoDeContas,
    admissao: Utils.Mes(2021, 2),
    salarioBase: 0,
    salarioBaseInicial: 2567,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1900, 1),
    comercial: true,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 700011,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.ExecutivoDeContas,
    admissao: Utils.Mes(2021, 2),
    salarioBase: 0,
    salarioBaseInicial: 2567,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1900, 1),
    comercial: true,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 700012,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.Vendedor,
    admissao: Utils.Mes(2021, 3),
    salarioBase: 0,
    salarioBaseInicial: 1965,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1900, 1),
    comercial: true,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 0,
    regiao: Regioes.SCSul,
  },
  {
    matricula: 700013,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.Vendedor,
    admissao: Utils.Mes(2021, 3),
    salarioBase: 0,
    salarioBaseInicial: 1965,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1900, 1),
    comercial: true,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 700014,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.Vendedor,
    admissao: Utils.Mes(2021, 1),
    salarioBase: 0,
    salarioBaseInicial: 1965,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1900, 1),
    comercial: true,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 700015,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.Vendedor,
    admissao: Utils.Mes(2021, 1),
    salarioBase: 0,
    salarioBaseInicial: 1965,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1900, 1),
    comercial: true,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 700016,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.Vendedor,
    admissao: Utils.Mes(2021, 1),
    salarioBase: 0,
    salarioBaseInicial: 1965,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1900, 1),
    comercial: true,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 700017,
    setor: 'COMERCIAL',
    nomeCargo: Cargos.Assistente_AnalistaComercial,
    admissao: Utils.Mes(2021, 1),
    salarioBase: 0,
    salarioBaseInicial: 2500,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1900, 1),
    comercial: true,
    estadoResidencia: 'RS',
    sexo: 'M',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 700018,
    setor: 'MARKETING',
    nomeCargo: Cargos.AnalistaMarketing,
    admissao: Utils.Mes(2021, 2),
    salarioBase: 0,
    salarioBaseInicial: 3000,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1900, 1),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'F',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 700019,
    setor: 'MARKETING',
    nomeCargo: Cargos.AnalistaSocialMidia,
    admissao: Utils.Mes(2021, 2),
    salarioBase: 0,
    salarioBaseInicial: 3000,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1900, 1),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'F',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
  {
    matricula: 700020,
    setor: 'MARKETING',
    nomeCargo: Cargos.AuxiliarDeMarketing,
    admissao: Utils.Mes(2021, 2),
    salarioBase: 0,
    salarioBaseInicial: 1656,
    funcaoGratificada: false,
    dataLimite: null,
    temAdicionalNoturno: true,
    dataNascimento: Utils.Mes(1900, 1),
    comercial: false,
    estadoResidencia: 'RS',
    sexo: 'F',
    qtdFilhos: 0,
    regiao: Regioes.GPOA,
  },
];
